/*
 * The model for our fruit. Could be generated by Swagger-codegen
 */
export class Fruit {

    name: string;
    taste: string;
    color: string;
    shape: string;
    type: string;
    unid: string;

    constructor() {}
}
